import type { ChecklistItemME, TipoEquipamento } from '@/types/maquinas'

const PEMT: ChecklistItemME[] = [
  { id: 'p01', categoria: 'Condições Gerais', descricao: 'Documentação da máquina presente (notas fiscais / identificação)' },
  { id: 'p02', categoria: 'Condições Gerais', descricao: 'Laudo de inspeção / manutenção vigente' },
  { id: 'p03', categoria: 'Condições Gerais', descricao: 'Manual do operador disponível na máquina' },
  { id: 'p04', categoria: 'Condições Gerais', descricao: 'Plaqueta de capacidade de carga fixada e legível' },
  { id: 'p05', categoria: 'Condições Gerais', descricao: 'Nível de óleo hidráulico adequado' },
  { id: 'p06', categoria: 'Condições Gerais', descricao: 'Carga da bateria / nível de combustível adequado' },
  { id: 'p07', categoria: 'Condições Gerais', descricao: 'Pneus sem cortes, deformações ou baixa calibragem' },
  { id: 'p08', categoria: 'Condições Gerais', descricao: 'Estrutura da plataforma sem danos visíveis' },
  { id: 'p09', categoria: 'Condições Gerais', descricao: 'Corrimãos e painéis de proteção em bom estado' },
  { id: 'p10', categoria: 'Condições Gerais', descricao: 'Porta de acesso funcional com fechamento adequado' },
  { id: 'p11', categoria: 'Condições Gerais', descricao: 'Painel de controles identificado e sem danos' },
  { id: 'p12', categoria: 'Condições Gerais', descricao: 'Movimentos de subida / descida funcionais' },
  { id: 'p13', categoria: 'Condições Gerais', descricao: 'Movimentos de translação funcionais (se aplicável)' },
  { id: 'p14', categoria: 'Condições Gerais', descricao: 'Sistema de nivelamento automático funcional (se aplicável)' },
  { id: 'p15', categoria: 'Condições Gerais', descricao: 'Luzes de sinalização e alertas funcionais' },
  { id: 'p16', categoria: 'Condições Gerais', descricao: 'Buzina / sinal sonoro funcional' },
  { id: 'p17', categoria: 'Condições Gerais', descricao: 'Freios de estacionamento funcionais' },
  { id: 'p18', categoria: 'Condições Gerais', descricao: 'Botão de parada de emergência funcional' },
  { id: 'p19', categoria: 'Condições Gerais', descricao: 'Dispositivo anti-queda funcional' },
  { id: 'p20', categoria: 'Condições Gerais', descricao: 'Sensores de segurança contra esmagamento funcionais' },
  { id: 'p21', categoria: 'Condições Gerais', descricao: 'Ponto de ancoragem para cinto de segurança disponível' },
  { id: 'p22', categoria: 'Condições Gerais', descricao: 'Extintor de incêndio na máquina (se exigido)' },
  { id: 'p23', categoria: 'Condições Gerais', descricao: 'Limpeza geral da máquina satisfatória' },
  { id: 'p24', categoria: 'Documentação do Operador', descricao: 'Operador com habilitação / certificado válido para PEMT' },
  { id: 'p25', categoria: 'Documentação do Operador', descricao: 'ASO (Atestado de Saúde Ocupacional) vigente' },
  { id: 'p26', categoria: 'Documentação do Operador', descricao: 'Treinamento específico para PEMT realizado e documentado' },
  { id: 'p27', categoria: 'Documentação do Operador', descricao: 'EPI adequado disponível e sendo utilizado (capacete, cinto, botina)' },
  { id: 'p28', categoria: 'Documentação do Operador', descricao: 'Ordem de Serviço assinada para a atividade' },
]

const EMPILHADEIRA: ChecklistItemME[] = [
  { id: 'e01', categoria: 'Condições Gerais', descricao: 'Documentação da máquina presente (notas fiscais / identificação)' },
  { id: 'e02', categoria: 'Condições Gerais', descricao: 'Laudo de inspeção / manutenção vigente' },
  { id: 'e03', categoria: 'Condições Gerais', descricao: 'Plaqueta de capacidade de carga visível e legível' },
  { id: 'e04', categoria: 'Condições Gerais', descricao: 'Combustível / carga da bateria adequado' },
  { id: 'e05', categoria: 'Condições Gerais', descricao: 'Nível de óleo hidráulico adequado' },
  { id: 'e06', categoria: 'Condições Gerais', descricao: 'Nível de óleo do motor adequado (se combustão)' },
  { id: 'e07', categoria: 'Condições Gerais', descricao: 'Sistema de refrigeração sem vazamentos' },
  { id: 'e08', categoria: 'Condições Gerais', descricao: 'Pneus / rodas em bom estado' },
  { id: 'e09', categoria: 'Condições Gerais', descricao: 'Garfos sem deformação, trincas ou desgaste excessivo' },
  { id: 'e10', categoria: 'Condições Gerais', descricao: 'Mastro sem deformações ou danos' },
  { id: 'e11', categoria: 'Condições Gerais', descricao: 'Sistema hidráulico sem vazamentos' },
  { id: 'e12', categoria: 'Condições Gerais', descricao: 'Correntes de elevação em bom estado e lubrificadas' },
  { id: 'e13', categoria: 'Condições Gerais', descricao: 'Movimentos de elevação, descida e inclinação funcionais' },
  { id: 'e14', categoria: 'Condições Gerais', descricao: 'Freio de serviço funcional' },
  { id: 'e15', categoria: 'Condições Gerais', descricao: 'Freio de estacionamento funcional' },
  { id: 'e16', categoria: 'Condições Gerais', descricao: 'Direção funcional e sem folgas excessivas' },
  { id: 'e17', categoria: 'Condições Gerais', descricao: 'Luzes dianteiras e traseiras funcionais' },
  { id: 'e18', categoria: 'Condições Gerais', descricao: 'Luz de aviso / giroflex funcional' },
  { id: 'e19', categoria: 'Condições Gerais', descricao: 'Buzina funcional' },
  { id: 'e20', categoria: 'Condições Gerais', descricao: 'Retrovisores em bom estado e ajustados' },
  { id: 'e21', categoria: 'Condições Gerais', descricao: 'Cinto de segurança do operador funcional' },
  { id: 'e22', categoria: 'Condições Gerais', descricao: 'Proteção do operador (overhead guard) em bom estado' },
  { id: 'e23', categoria: 'Condições Gerais', descricao: 'Extintor de incêndio presente e carregado' },
  { id: 'e24', categoria: 'Condições Gerais', descricao: 'Limpeza geral satisfatória' },
  { id: 'e25', categoria: 'Documentação do Operador', descricao: 'Operador com habilitação / certificado válido para empilhadeira' },
  { id: 'e26', categoria: 'Documentação do Operador', descricao: 'ASO (Atestado de Saúde Ocupacional) vigente' },
  { id: 'e27', categoria: 'Documentação do Operador', descricao: 'Treinamento específico realizado e documentado' },
  { id: 'e28', categoria: 'Documentação do Operador', descricao: 'EPI adequado em uso (capacete, botina, colete)' },
]

const CAMINHAO: ChecklistItemME[] = [
  { id: 'c01', categoria: 'Condições Gerais', descricao: 'CRLV do veículo vigente' },
  { id: 'c02', categoria: 'Condições Gerais', descricao: 'Tacógrafo calibrado e funcionando (se obrigatório)' },
  { id: 'c03', categoria: 'Condições Gerais', descricao: 'Pneus com sulcos adequados e sem danos visíveis' },
  { id: 'c04', categoria: 'Condições Gerais', descricao: 'Step-ney / estepe em boas condições' },
  { id: 'c05', categoria: 'Condições Gerais', descricao: 'Sistema de freio funcional (pedal e freio de mão)' },
  { id: 'c06', categoria: 'Condições Gerais', descricao: 'Luzes dianteiras (farol alto, baixo e de presença) funcionais' },
  { id: 'c07', categoria: 'Condições Gerais', descricao: 'Luzes traseiras (lanterna, freio, ré e pisca) funcionais' },
  { id: 'c08', categoria: 'Condições Gerais', descricao: 'Setas e pisca-alerta funcionais' },
  { id: 'c09', categoria: 'Condições Gerais', descricao: 'Espelhos retrovisores presentes e ajustados' },
  { id: 'c10', categoria: 'Condições Gerais', descricao: 'Limpadores de para-brisa funcionais' },
  { id: 'c11', categoria: 'Condições Gerais', descricao: 'Vidros sem trincas que comprometam visibilidade' },
  { id: 'c12', categoria: 'Condições Gerais', descricao: 'Buzina funcional' },
  { id: 'c13', categoria: 'Condições Gerais', descricao: 'Cinto de segurança funcional' },
  { id: 'c14', categoria: 'Condições Gerais', descricao: 'Extintor de incêndio carregado e no prazo' },
  { id: 'c15', categoria: 'Condições Gerais', descricao: 'Kit de primeiros socorros presente' },
  { id: 'c16', categoria: 'Condições Gerais', descricao: 'Kit de segurança (triângulo, chave de roda, macaco) presente' },
  { id: 'c17', categoria: 'Condições Gerais', descricao: 'Nível de óleo do motor adequado' },
  { id: 'c18', categoria: 'Condições Gerais', descricao: 'Nível de fluido de freio adequado' },
  { id: 'c19', categoria: 'Condições Gerais', descricao: 'Nível de água do radiador adequado' },
  { id: 'c20', categoria: 'Condições Gerais', descricao: 'Nível de óleo de direção hidráulica adequado' },
  { id: 'c21', categoria: 'Condições Gerais', descricao: 'Carroceria / estrutura sem danos estruturais visíveis' },
  { id: 'c22', categoria: 'Condições Gerais', descricao: 'Sistema de basculamento funcional (se aplicável)' },
  { id: 'c23', categoria: 'Condições Gerais', descricao: 'Para-choque traseiro de proteção presente' },
  { id: 'c24', categoria: 'Condições Gerais', descricao: 'Faixas reflexivas de sinalização presentes e em bom estado' },
  { id: 'c25', categoria: 'Condições Gerais', descricao: 'Limpeza geral satisfatória' },
  { id: 'c26', categoria: 'Documentação do Motorista', descricao: 'Motorista com CNH válida e categoria compatível com o veículo' },
  { id: 'c27', categoria: 'Documentação do Motorista', descricao: 'ASO (Atestado de Saúde Ocupacional) vigente' },
  { id: 'c28', categoria: 'Documentação do Motorista', descricao: 'Curso de direção defensiva vigente' },
  { id: 'c29', categoria: 'Documentação do Motorista', descricao: 'Seguro obrigatório (DPVAT) vigente' },
  { id: 'c30', categoria: 'Documentação do Motorista', descricao: 'EPI adequado em uso (colete refletivo, botina)' },
]

const GUINDAUTO: ChecklistItemME[] = [
  { id: 'g01', categoria: 'Condições Gerais', descricao: 'CRLV do veículo base vigente' },
  { id: 'g02', categoria: 'Condições Gerais', descricao: 'Laudo de inspeção / manutenção do guindauto vigente' },
  { id: 'g03', categoria: 'Condições Gerais', descricao: 'Plano de içamento disponível para a operação' },
  { id: 'g04', categoria: 'Condições Gerais', descricao: 'Plaqueta com carga máxima por raio / lança visível e legível' },
  { id: 'g05', categoria: 'Condições Gerais', descricao: 'Nível de óleo do motor do veículo base adequado' },
  { id: 'g06', categoria: 'Condições Gerais', descricao: 'Nível de óleo hidráulico adequado' },
  { id: 'g07', categoria: 'Condições Gerais', descricao: 'Pneus do veículo base em bom estado' },
  { id: 'g08', categoria: 'Condições Gerais', descricao: 'Estrutura da lança sem deformações, trincas ou corrosão excessiva' },
  { id: 'g09', categoria: 'Condições Gerais', descricao: 'Cabo de aço sem fios rompidos, sem deformação (kink) e lubrificado' },
  { id: 'g10', categoria: 'Condições Gerais', descricao: 'Gancho com trava de segurança funcional' },
  { id: 'g11', categoria: 'Condições Gerais', descricao: 'Polias em bom estado e lubrificadas' },
  { id: 'g12', categoria: 'Condições Gerais', descricao: 'Estabilizadores / outriggers funcionais e apoiados corretamente' },
  { id: 'g13', categoria: 'Condições Gerais', descricao: 'Bloqueador / limitador de carga funcional (se disponível)' },
  { id: 'g14', categoria: 'Condições Gerais', descricao: 'Limitador de altura de gancho funcional' },
  { id: 'g15', categoria: 'Condições Gerais', descricao: 'Controles de operação identificados e funcionais' },
  { id: 'g16', categoria: 'Condições Gerais', descricao: 'Luzes do veículo base funcionais' },
  { id: 'g17', categoria: 'Condições Gerais', descricao: 'Giroflex / luz de advertência funcional' },
  { id: 'g18', categoria: 'Condições Gerais', descricao: 'Buzina do veículo funcional' },
  { id: 'g19', categoria: 'Condições Gerais', descricao: 'Comunicação visual entre operador e sinaleiro estabelecida' },
  { id: 'g20', categoria: 'Condições Gerais', descricao: 'Área de operação sinalizada e isolada adequadamente' },
  { id: 'g21', categoria: 'Condições Gerais', descricao: 'Extintor de incêndio presente e carregado' },
  { id: 'g22', categoria: 'Condições Gerais', descricao: 'Correntes / cintas de içamento inspecionadas (se utilizadas)' },
  { id: 'g23', categoria: 'Condições Gerais', descricao: 'Sapatilhas e manilhas em bom estado (se utilizadas)' },
  { id: 'g24', categoria: 'Condições Gerais', descricao: 'Distância segura de redes elétricas verificada' },
  { id: 'g25', categoria: 'Condições Gerais', descricao: 'Limpeza geral satisfatória' },
  { id: 'g26', categoria: 'Documentação do Operador', descricao: 'Operador / motorista com habilitação compatível' },
  { id: 'g27', categoria: 'Documentação do Operador', descricao: 'ASO (Atestado de Saúde Ocupacional) vigente' },
  { id: 'g28', categoria: 'Documentação do Operador', descricao: 'Treinamento em içamento de cargas realizado e documentado' },
  { id: 'g29', categoria: 'Documentação do Operador', descricao: 'ART do plano de içamento disponível (quando aplicável)' },
  { id: 'g30', categoria: 'Documentação do Operador', descricao: 'EPI adequado em uso (capacete, luvas, botina, colete)' },
]

const MANIPULADORA: ChecklistItemME[] = [
  { id: 'm01', categoria: 'Condições Gerais', descricao: 'Documentação da máquina presente (notas fiscais / identificação)' },
  { id: 'm02', categoria: 'Condições Gerais', descricao: 'Laudo de inspeção / manutenção vigente' },
  { id: 'm03', categoria: 'Condições Gerais', descricao: 'Plaqueta de capacidade de carga visível e legível' },
  { id: 'm04', categoria: 'Condições Gerais', descricao: 'Nível de combustível adequado' },
  { id: 'm05', categoria: 'Condições Gerais', descricao: 'Nível de óleo hidráulico adequado' },
  { id: 'm06', categoria: 'Condições Gerais', descricao: 'Nível de óleo do motor adequado' },
  { id: 'm07', categoria: 'Condições Gerais', descricao: 'Pneus em bom estado (sem cortes ou deformações)' },
  { id: 'm08', categoria: 'Condições Gerais', descricao: 'Estrutura do braço telescópico sem danos visíveis' },
  { id: 'm09', categoria: 'Condições Gerais', descricao: 'Sistema hidráulico sem vazamentos' },
  { id: 'm10', categoria: 'Condições Gerais', descricao: 'Movimentos telescópicos (extensão / retração) funcionais' },
  { id: 'm11', categoria: 'Condições Gerais', descricao: 'Acessório fixado corretamente (garfo, caçamba, lança, etc.)' },
  { id: 'm12', categoria: 'Condições Gerais', descricao: 'Sistema de nivelamento / estabilização funcional (se disponível)' },
  { id: 'm13', categoria: 'Condições Gerais', descricao: 'Freio de serviço funcional' },
  { id: 'm14', categoria: 'Condições Gerais', descricao: 'Freio de estacionamento funcional' },
  { id: 'm15', categoria: 'Condições Gerais', descricao: 'Direção funcional e responsiva' },
  { id: 'm16', categoria: 'Condições Gerais', descricao: 'Cabine / ROPS em bom estado' },
  { id: 'm17', categoria: 'Condições Gerais', descricao: 'Cinto de segurança do operador funcional' },
  { id: 'm18', categoria: 'Condições Gerais', descricao: 'Luzes dianteiras e traseiras funcionais' },
  { id: 'm19', categoria: 'Condições Gerais', descricao: 'Giroflex / luz de advertência funcional' },
  { id: 'm20', categoria: 'Condições Gerais', descricao: 'Buzina funcional' },
  { id: 'm21', categoria: 'Condições Gerais', descricao: 'Retrovisores presentes e ajustados' },
  { id: 'm22', categoria: 'Condições Gerais', descricao: 'Câmera de ré / espelho de visibilidade traseira funcional' },
  { id: 'm23', categoria: 'Condições Gerais', descricao: 'Extintor de incêndio presente e carregado' },
  { id: 'm24', categoria: 'Condições Gerais', descricao: 'Área de trabalho verificada (obstáculos, fiação elétrica)' },
  { id: 'm25', categoria: 'Condições Gerais', descricao: 'Limpeza geral satisfatória' },
  { id: 'm26', categoria: 'Documentação do Operador', descricao: 'Operador com habilitação / certificado válido para manipuladora' },
  { id: 'm27', categoria: 'Documentação do Operador', descricao: 'ASO (Atestado de Saúde Ocupacional) vigente' },
  { id: 'm28', categoria: 'Documentação do Operador', descricao: 'Treinamento específico para manipuladora realizado e documentado' },
  { id: 'm29', categoria: 'Documentação do Operador', descricao: 'EPI adequado em uso (capacete, botina, colete, luva)' },
]

const RETROESCAVADEIRA: ChecklistItemME[] = [
  { id: 'r01', categoria: 'Condições Gerais', descricao: 'Nível de combustível adequado' },
  { id: 'r02', categoria: 'Condições Gerais', descricao: 'Nível de óleo do motor adequado' },
  { id: 'r03', categoria: 'Condições Gerais', descricao: 'Nível de óleo hidráulico adequado' },
  { id: 'r04', categoria: 'Condições Gerais', descricao: 'Nível de fluido de arrefecimento (radiador) adequado' },
  { id: 'r05', categoria: 'Condições Gerais', descricao: 'Correia do alternador / ventilador em bom estado' },
  { id: 'r06', categoria: 'Condições Gerais', descricao: 'Filtros de ar sem obstrução excessiva' },
  { id: 'r07', categoria: 'Condições Gerais', descricao: 'Pneus / esteiras em bom estado' },
  { id: 'r08', categoria: 'Condições Gerais', descricao: 'Estrutura do chassis sem danos estruturais visíveis' },
  { id: 'r09', categoria: 'Condições Gerais', descricao: 'Lança / braço frontal (carregadeira) sem deformações' },
  { id: 'r10', categoria: 'Condições Gerais', descricao: 'Caçamba frontal sem danos excessivos e dentes íntegros' },
  { id: 'r11', categoria: 'Condições Gerais', descricao: 'Braço / lança traseira sem deformações' },
  { id: 'r12', categoria: 'Condições Gerais', descricao: 'Caçamba traseira sem danos excessivos e dentes íntegros' },
  { id: 'r13', categoria: 'Condições Gerais', descricao: 'Cilindros hidráulicos sem vazamentos' },
  { id: 'r14', categoria: 'Condições Gerais', descricao: 'Mangueiras hidráulicas sem vazamentos ou danos' },
  { id: 'r15', categoria: 'Condições Gerais', descricao: 'Estabilizadores traseiros funcionais' },
  { id: 'r16', categoria: 'Condições Gerais', descricao: 'Articulações com lubrificação adequada' },
  { id: 'r17', categoria: 'Condições Gerais', descricao: 'Sistema de freio do deslocamento funcional' },
  { id: 'r18', categoria: 'Condições Gerais', descricao: 'Freio de estacionamento funcional' },
  { id: 'r19', categoria: 'Condições Gerais', descricao: 'Controles de operação identificados e funcionais' },
  { id: 'r20', categoria: 'Condições Gerais', descricao: 'ROPS / FOPS em bom estado e sem deformações' },
  { id: 'r21', categoria: 'Condições Gerais', descricao: 'Cinto de segurança do operador funcional' },
  { id: 'r22', categoria: 'Condições Gerais', descricao: 'Luzes de trabalho (dianteiras e traseiras) funcionais' },
  { id: 'r23', categoria: 'Condições Gerais', descricao: 'Giroflex / luz de advertência funcional' },
  { id: 'r24', categoria: 'Condições Gerais', descricao: 'Buzina funcional' },
  { id: 'r25', categoria: 'Condições Gerais', descricao: 'Extintor de incêndio presente e carregado' },
  { id: 'r26', categoria: 'Documentação', descricao: 'Documentação da máquina presente (notas fiscais / identificação)' },
  { id: 'r27', categoria: 'Documentação', descricao: 'Laudo de inspeção / manutenção vigente' },
  { id: 'r28', categoria: 'Documentação', descricao: 'Operador com habilitação / certificado válido para retroescavadeira' },
  { id: 'r29', categoria: 'Documentação', descricao: 'ASO (Atestado de Saúde Ocupacional) vigente' },
  { id: 'r30', categoria: 'Documentação', descricao: 'Treinamento específico para retroescavadeira realizado e documentado' },
  { id: 'r31', categoria: 'Documentação', descricao: 'EPI adequado em uso (capacete, botina, luva, colete)' },
  { id: 'r32', categoria: 'Documentação', descricao: 'Área de trabalho verificada (interferências subterrâneas e aéreas)' },
  { id: 'r33', categoria: 'Documentação', descricao: 'Sinalização e isolamento da área de trabalho adequados' },
  { id: 'r34', categoria: 'Documentação', descricao: 'Autorizações necessárias para escavação obtidas (se aplicável)' },
  { id: 'r35', categoria: 'Documentação', descricao: 'Limpeza geral satisfatória' },
]

export const CHECKLIST_POR_TIPO: Record<TipoEquipamento, ChecklistItemME[]> = {
  pemt:            PEMT,
  empilhadeira:    EMPILHADEIRA,
  caminhao:        CAMINHAO,
  guindauto:       GUINDAUTO,
  manipuladora:    MANIPULADORA,
  retroescavadeira: RETROESCAVADEIRA,
}
